#!/bin/bash
sudo apt install -y python3 python-dev
sudo apt install -y git libffi-dev libssl-dev gcc libc6-dev make python3-pip git virtualenv

sudo curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh
sudo systemctl enable docker

virtualenv env -p python3
source env/bin/activate
pip install --upgrade pip
pip install invoke
pip install boto3
pip install docker


git clone https://github.com/obedmacallums/parkingfile_ssh.git
cd parkingfile_ssh
invoke start-ssh
