#!/bin/bash
sudo apt install -y python3 python-dev
sudo apt install -y git py-pip libffi-dev openssl-dev gcc libc-dev make python3-pip git virtualenv

sudo curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh

virtualenv env -p python3
source env/bin/activate
pip install invoke
pip install boto3
pip install docker
pip install docker-compose

sudo git clone https://github.com/obedmacallums/parkingfile_ssh.git
cd parkingfile_ssh
invoke start-ssh
